### PR TITLE
Player class, Added some comments, moved README

### PR DESCRIPTION
**Pull request by killjoy01**
well that was fun.

### CODE REVIEW

**Comment by Ecophagy** [comment]
First off, you need to move this to a different branch. Master is for definitely finished and working releases. 

Other things:
-Why did you move the README? I'm like 95% sure it was in the right place already

In Player.cs:
-mainName should be their forum name, even if no-one would usually call them it.
-We don't need hoursSinceLastPost since we can work it out from lastPost.
-Not sure what numberOnVoteCount is for. why wouldn't we just use mainName as a key?
-I don't like totalPlayercount existing: it's outside the scope of each player to know how many players there are in total. Total number of players can be found by checking the size of the list the player objects will be stored in.
-What are the "a" prefixes for?
-Single voter Constructor should just call the Multi-voter constructor with numberofVotes=1 (to avoid the duplication of code across the two constructors)
-lastPost should probably just initialise to Null rather than a valid (but useless) value.
-The Destructor is unnecessary (C# will garbage collection will handle clearing up the nickname list). It also doesn't actually do anything since it will only decrement the total player numbers if there is somehow a negative number of players! [We don't need to decrement the value if we remove it completely]

In PostList:
-Yes it rounds, that's what the Math.Celing() bit does. Probably shouldn't add comments if you're not sure :p

In VoteCount:
the new playerNames dictionary is intended to replace List<string> playerNames.  It also doesn't need to be an OrderedDictionary, a regular one will do fine. 
populatePlayerNicknameList doesn't really do anything. It just creates a bunch of Player objects that just...disappear when the function ends. I'm also pretty sure it wants to be i++ not ++I, otherwise you'll try and access beyond the end of the list. In any case, even if it did return something like the list of Players it created, it's a super clunky way to start creating a dictionary. 
Instead, we want a dictionary where the keys are populated exactly as the current playerlist is, then we iterate over some extra column in the gui to add nicknames to the corresponding value.

****

Most importantly, make a new branch. Also it's not really worth opening  a pull request for this  kind of work-in-progress stuff: you want to keep it to your own branch/fork until whatever overarching feature you're working on is done. Either that or put something small, useful, and discrete (like JUST the Player class) if other people need them. At the moment it's a halfway between useful extras and a partially finished feature.

**Comment by Ecophagy** [comment]
Oh bugger, I could have made those comments in line on the files. Lesson learned for next time!

**Comment by killjoy01** [comment]
-I've never branched before, so I'll do that next time. 

-i've moved the readme so I knew what needed fixing. I should say I made a new text file and called it read me. 

Player.cs
mainName: yeah. We'll probably extract the name and put it in there. 
hoursSinceLastPost: yeah I was thinking about that. That could probably be a subroutine that looks from the most recent post backwards to see when everyone left posted.
number: I suppose I just generally prefer numeric keys for things. Name will work just fine. 
totalPlayers: that's more for debugging and memory management for if the project gets big. It would not be used by the user, just by us . Not strictly necessary right now

**Comment by Ecophagy** [comment]
-I have to insist on making a new branch now, as well as the future.

-Moving readme for personal local use is fine. Committing and pushing that move is not.

-Hungarian Notation: Don't use it. It was useful in the old days when it was difficult to work out what was what, but that's not necessary any more. Also it's the sort of thing which if you do use, has to be consistent. 

PostList: Don't add those sorts of comments. Ask the person who wrote the code, and get them to clarify with a comment if it's not clear. Speculative comments don't add much valule.

VoteCount: Ok. Pull requests are for done and dusted stuff really, so there's not much point opening one for WIP stuff.

*****

I'm going to close this request, sort out some branches, and clarify with you what your goal is.

**Pull request closed without merging**
